import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";
import Head from 'next/head';
const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Meeting Schedular",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
     <meta name="google-site-verification" content="TdMZcCgup5n4hjeG2MIGCa8DzJj41atsbr3-gy55xIc" />
      </Head>
      <body className={inter.className}>
      <Toaster/>
      {children}</body>
    </html>
  );
}
